# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d68bf1a5452afd81bb121ccb092014be998bc2f3ad92835eca955771ffe03bc196d095a00ad6d29baeaa92faccc872612ca02b96737e9f7f70171851569a6373

test:
  secret_key_base: 5344959e5b418281083ea21d166fa90427b83d78fa7a9447de799d63fecbbeeaab4281e95e90e270f893788518c6478d6d92277d4f030d31a738f2c1a5eda6e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
